### PR TITLE
Feature/validation and polishing

### PR DESCRIPTION
**Pull request by manudss**
- Fix validations function to works with customs decorators. #13 
- Add default value for labels. To don't enable all labels by default #17 
- improve display of descriptions with tooltips : 
image

Thanks for first PR. I woulds to continue to improve it : to add decorators functionality. We will need to discuss this.

### CODE REVIEW

**Comment by smartinio** [comment]
Hey, can you record a video of the changes? I don't use bitbucket anymore and it seems the extension isn't compatible with the version available for free at bitbucket.org.

**Comment by manudss** [comment]
@smartinio Yes, you're right, it does not work for bitbucket.org. 

All this changed was also included in the second PR. So this PR includes only a better display for description, and fix for validation function (when validate a comment).

**Comment by smartinio** [comment]
Hey @manudss! I've added CI steps for code checks to run jest & prettier. Please rebase your branches and run `yarn chores` locally to make sure they'll pass CI

**Comment by manudss** [comment]
These changes were already changed in next PR #20.

**Pull request closed without merging**
